# Generated by Django 5.2.8 on 2025-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('barcode', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
