# Generated by Django 5.2.8 on 2025-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pattern_image',
            field=models.ImageField(blank=True, null=True, upload_to='pattern_outputs/'),
        ),
    ]
